behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        network_settings:
          normalize: True
          hidden_units: 256
          num_layers: 2
    max_steps: 200000
    summary_freq: 2000
    threaded: True
